# Generated by Django 5.2.1 on 2025-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obj_name', models.CharField(max_length=200)),
                ('Obj_rate', models.IntegerField()),
                ('Obj_quantity', models.IntegerField()),
                ('Obj_price', models.IntegerField()),
            ],
        ),
    ]
