# Generated by Django 5.2.1 on 2025-05-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_shopping_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_object',
            name='Obj_Image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
    ]
