# Generated by Django 5.1.7 on 2025-05-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_picture',
            name='Category_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.category'),
        ),
    ]
