# Generated by Django 5.1.7 on 2025-05-17 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_profile_picture_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_object_container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sell_Object_name', models.CharField(max_length=200)),
                ('Sell_Object_Image', models.ImageField(blank=True, null=True, upload_to='Sell_Object/')),
                ('Sell_Object_rate', models.IntegerField()),
                ('Sell_Object_quantity', models.IntegerField()),
                ('Sell_Object_price', models.IntegerField()),
                ('Sell_Object_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Backend.category')),
            ],
        ),
    ]
