# Generated by Django 5.1.7 on 2025-05-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_sell_object_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_object_container',
            name='Sell_Object_rate',
        ),
        migrations.AddField(
            model_name='sell_object_container',
            name='Sell_object_Discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
